[package]
name = "whack-a-mole"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inline-vbs = "0.4.0"
tokio = { version = "1.28.2", features = ["rt", "rt-multi-thread", "macros", "time"] }
